name: Deploy Base Configuration

on:
  # Deploy on Manual trigger
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.6  # Specify the version you want to use

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Apply
        run: |
          cd terraform
          terraform init
          terraform plan -var-file=dev.tfvars
          echo "Deploying Lambda..."
          terraform apply -var-file=dev.tfvars -auto-approve
